packages:
  - name: property_stewards
    functions:
      - name: api
        runtime: nodejs:18
        web: true
        main: index.js
        environment:
          DB_HOST: "${DB_HOST}"
          DB_PORT: "${DB_PORT}"
          DB_USER: "${DB_USER}"
          DB_PASSWORD: "${DB_PASSWORD}"
          DB_NAME: "${DB_NAME}"
          WASSENGER_API_KEY: "${WASSENGER_API_KEY}"
          WASSENGER_DEVICE_ID: "${WASSENGER_DEVICE_ID}"
          OPENAI_API_KEY: "${OPENAI_API_KEY}"
          WHATSAPP_PROVIDER: "${WHATSAPP_PROVIDER}"
        limits:
          timeout: 30000
          memory: 512