name: end-to-end-property-inspection-system
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_REPO
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
  - key: WASSENGER_API_KEY
    scope: RUN_AND_BUILD_TIME
  - key: WASSENGER_DEVICE_ID
    scope: RUN_AND_BUILD_TIME
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
  - key: WHATSAPP_PROVIDER
    scope: RUN_AND_BUILD_TIME
  - key: WHATSAPP_API_URL
    scope: RUN_AND_BUILD_TIME
  - key: WHATSAPP_BUSINESS_ACCOUNT_ID
    scope: RUN_AND_BUILD_TIME
  - key: WHATSAPP_VERIFY_TOKEN
    scope: RUN_AND_BUILD_TIME
  - key: WHATSAPP_PHONE_NUMBER_ID
    scope: RUN_AND_BUILD_TIME
  - key: WHATSAPP_ACCESS_TOKEN
    scope: RUN_AND_BUILD_TIME
  - key: DIGITALOCEAN_TOKEN
    scope: RUN_AND_BUILD_TIME
  - key: sslmode
    scope: RUN_AND_BUILD_TIME
  routes:
  - path: /